# Generated by Django 3.1.1 on 2020-09-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drrr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(default='john due', max_length=50),
        ),
    ]
