# Generated by Django 3.1.1 on 2020-09-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drrr', '0002_auto_20200924_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='uuid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
